namespace DemoHub.Common.Enums
{
    /// <Summary>
    /// Represents a collection of CHESS enumaration values.
    /// </Summary>
    public class ChessEnums
    {
        /// <Summary>
        /// Represents a message group.
        /// </Summary>
        #region Message categories
        public enum MessageCategory
        {
            Unsupported,
            /// <Summary>
            /// Payment Facilities
            /// </Summary>
            PaymentFacilities,
            /// <Summary>
            /// Holder Maintenance
            /// </Summary>
            HolderMaintenance,
            /// <Summary>
            /// Applications
            /// </Summary>
            Applications,
            /// <Summary>
            /// Redemptions
            /// </Summary>
            Redemptions,
            /// <Summary>
            /// Switches
            /// </Summary>
            Switches,
            /// <Summary>
            /// Order Maintenance
            /// </Summary>
            OrderMaintenance,
            /// <Summary>
            /// Income Statements
            /// </Summary>
            IncomeStatements,
            /// <Summary>
            /// Distribution Reinvestment Plans (DRP) Elections
            /// </Summary>
            DrpElections,
            /// <Summary>
            /// Regular Payment Plans (RPP) Elections(not currently in production)
            /// </Summary>
            RppElections,
            /// <Summary>
            /// Distribution Reinvestment Plans (DRP)
            /// </Summary>
            Drp,
            /// <Summary>
            /// Conversions
            /// </Summary>
            Conversions,
            /// <Summary>
            /// Enquiries
            /// </Summary>
            Enquiries,
            /// <Summary>
            /// Reporting
            /// </Summary>
            Reporting,
            /// <Summary>
            /// Settlement
            /// </Summary>
            Settlement,
            /// <Summary>
            /// Payments
            /// </Summary>
            Payments
        }
        #endregion Message categories

        /// <Summary>
        /// Represents an investor type.
        /// </Summary>
        #region Investor type
        public enum InvestorType
        {
            Unknown,
            /// <Summary>
            /// Individual
            /// </Summary>
            I,
            /// <Summary>
            /// Corporation
            /// </Summary>
            C,
            /// <Summary>
            /// Trust
            /// </Summary>
            T,
            /// <Summary>
            /// Partnership
            /// </Summary>
            P,
            /// <Summary>
            /// Superannuation fund
            /// </Summary>
            S,
            /// <Summary>
            /// Deceased individual
            /// </Summary>
            D,
            /// <Summary>
            /// Government organisation
            /// </Summary>
            G,
            /// <Summary>
            /// Other non-individual
            /// </Summary>
            O
        }
        #endregion Investor type

        /// <Summary>
        /// Represents an individual message type.
        /// </Summary>
        #region CHESS Message Types
        //public enum MessageType
        //{
        //    DemandSingleEntryCHESStoCHESSTransferRequest = 1,
        //    EffectedDemandSingleEntryCHESStoCHESSTransfer = 2,
        //    TransferorSubmittedDemandTransfer = 3,
        //    EffectedTransferorSubmittedTransfer = 4,
        //    DemandDualEntryCHESStoCHESSTransferRequest = 5,
        //    EffectedDemandDualEntryCHESStoCHESS = 6,
        //    DemandCHESStoIssuerSponsoredTransferRequest = 7,
        //    EffectedCHESStoRegistryMovement = 8,
        //    DemandCHESStoCertificatedTransferRequest = 9,
        //    AppliedTransferorSubmittedTransfer = 10,
        //    CHESStoIssuerSponsoredConversionRequest = 11,
        //    UnmatchedDemandDualEntryCHESStoCHESS = 12,
        //    CHESStoCertificatedConversionRequest = 13,
        //    IssuerSponsoredtoCHESSTransferRequest = 14,
        //    AcceptedRegistrytoCHESSMovementRequest = 15,
        //    IssuerSponsoredtoCHESSConversionRequest = 16,
        //    EffectedSecuritiesTransformation = 17,
        //    CertificatedtoCHESSConversionRequest = 18,
        //    ASXClearAcceptedCollateral = 19,
        //    CertificatedtoCHESSTransferRequest = 20,
        //    EffectedHoldingAdjustment = 21,
        //    ASXClearCollateralRemovalRequest = 22,
        //    RejectedDemandDualEntryCHESStoCHESSTransfer = 23,
        //    SingleEntryTransferRequest = 24,
        //    CollateralCreationRequest = 25,
        //    CreatedCollateral = 26,
        //    CollateralRemovalRequest = 27,
        //    ReducedCollateral = 28,
        //    TakeoverAcceptance = 29,
        //    EffectedTakeoverAcceptance = 30,
        //    EffectedTakeoverTransfer = 31,
        //    OfferorTakeoverAcceptanceRejection = 32,
        //    OfferorTakeoverAcceptanceNotification = 33,
        //    DemandDualEntryCHESStoCHESSTransferCancellationRequest = 34,
        //    ReversedTakeoverAcceptance = 35,
        //    AcceptedCollateralRemovalRequest = 36,
        //    CollateralRelease = 37,
        //    CancelledDemandDualEntryTransferRequest = 38,
        //    EffectedSecurityCodeChange = 39,
        //    FullDualEntryCHESStoCHESSTransfer = 40,
        //    FullCHESStoCertificatedTransfer = 41,
        //    FullCertificatedtoCHESSTransfer = 42,
        //    FullCertificatedtoCHESSConversion = 43,
        //    FullIssuerSponsoredtoCHESSTransfer = 44,
        //    FullIssuerSponsoredtoCHESSConversion = 45,
        //    FullCHESStoIssuerSponsoredTransfer = 46,
        //    FullCHESStoCertificatedConversion = 47,
        //    FullCHESStoIssuerSponsoredConversion = 48,
        //    FullSingleEntryCHESStoCHESSTransfer = 49,
        //    RejectedRegistrytoCHESSMovement = 50,
        //    RejectedCollateralRemoval = 51,
        //    RejectedRegistrationDetailsUpdate = 52,
        //    AdjustedSubposition = 53,
        //    EffectedParticipantTransaction = 54,
        //    TakeoverAcceptanceRemovalRequest = 55,
        //    AcceptedTakeoverAcceptanceRemovalRequest = 56,
        //    RejectedTakeoverAcceptanceRemovalRequest = 57,
        //    FullTransferorSubmittedDemandTransfer = 58,
        //    OfferorTakeoverAcceptanceRemovalNotification = 59,
        //    PriceRegistration = 60,
        //    SecurityDetail = 61,
        //    PriceRegistrationNotification = 62,
        //    PriceNotificationAcceptance = 63,
        //    DualEntrySettlementNotification = 64,
        //    UnmatchedDualEntrySettlementNotification = 65,
        //    CPCollateralRemovalAuthorisation = 66,
        //    CollateralRemovalNotification = 67,
        //    SingleEntrySettlementCHESStoCHESSTransferRequest = 68,
        //    ScheduledSingleEntrySettlementCHESStoCHESSTransfer = 69,
        //    ScheduledSettlementCHESStoCHESSTransferRequest = 70,
        //    CollateralCreationAcceptanceAdvice = 71,
        //    CPCollateralRemovalRejection = 72,
        //    CPCollateralRemovalAcceptanceAdvice = 73,
        //    CancelledSettlementInstruction = 74,
        //    CancelledChangeSettlementInstructionRequest = 75,
        //    SingleEntrySettlementCHESStoCHESSTransferCancellationRequest = 76,
        //    CPCollateralRemovalRejectionAdvice = 77,
        //    ChangeSettlementInstructionRequest = 78,
        //    UnmatchedChangeSettlementInstructionRequest = 79,
        //    ChangeSettlementInstructionCancellationRequest = 80,
        //    RescheduledSettlementInstruction = 81,
        //    MaintainSettlementInstructionRequest = 82,
        //    UpdatedSettlementInstruction = 83,
        //    AdjustedSettlementInstruction = 84,
        //    DualEntrySettlementCancellationRequest = 85,
        //    RequestedSettlementInstructionChange = 86,
        //    DualEntrySettlementCancellationRemoval = 87,
        //    RemovedDualEntrySettlementInstructionCancellationRequest = 88,
        //    ScheduledNetObligation = 89,
        //    DualEntrySettlementNotificationCancellationRequest = 90,
        //    ReinstatedTrade = 91,
        //    NettedTrade = 92,
        //    IsolateCounterpartyRequest = 93,
        //    CancelledNetObligation = 94,
        //    AccruedSettlementInstruction = 95,
        //    EffectedCPTransaction = 96,
        //    EffectedNetSettlementMovement = 97,
        //    ProjectedCumEntitlementPosition = 98,
        //    ProjectedFundsObligation = 99,
        //    ProjectedHoldingPosition = 100,
        //    CancelledFundsObligation = 101,
        //    SettledSettlementInstruction = 102,
        //    ParticipantCounterpartyBalance = 103,
        //    CollateralRemovalRejectionAdvice = 104,
        //    TradeRegistrationRequest = 105,
        //    SuspendedSettlementInstruction = 106,
        //    NotifiedTrade = 107,
        //    ScheduledDualEntrySettlementInstruction = 108,
        //    CPCollateralRemovalAuthorisationRequest = 109,
        //    EffectedNetFundsMovement = 110,
        //    EffectedRegistrytoCHESSConversion = 111,
        //    EffectedRegistrytoCHESSTransfer = 112,
        //    CollateralCreationRejectionAdvice = 113,
        //    UnmatchedDualEntrySettlementInstructionCancellationRequest = 114,
        //    FullSettlementInstruction = 115,
        //    CollateralRemovaltoCPNotification = 116,
        //    TradeRegistrationAcceptance = 117,
        //    NetTrustAmountMovements = 118,
        //    FullAdjustedSettlementInstruction = 119,
        //    PredictedPartialFailAdvice = 120,
        //    Part_SettledSettlementInstruction = 121,
        //    UnmatchedDualEntryRequest = 122,
        //    BlockTradeRequest = 123,
        //    BlockedTrade = 124,
        //    UnblockTradeRequest = 125,
        //    UnblockedTrade = 126,
        //    NewRegistrationDetails = 127,
        //    AcceptedNewRegistrationDetails = 128,
        //    RegistrationDetailsUpdateRequest = 129,
        //    LockedCHESSHolding = 130,
        //    UnlockedCHESSHolding = 131,
        //    AcceptedRegistrationDetailsUpdate = 132,
        //    AuthorisedRegistrationDetails = 133,
        //    HolderDetail = 134,
        //    HolderHistory = 135,
        //    UserDetail = 136,
        //    UserHistory = 137,
        //    PaymentFacilityDetail = 138,
        //    PaymentFacilityHistory = 139,
        //    ReportingRequestDetail = 140,
        //    CreatedPaymentFacility = 141,
        //    AppliedPaymentFacilityUpdate = 142,
        //    CancelledPaymentFacility = 143,
        //    ChangeControllingParticipantRequest = 144,
        //    AcceptedChangeControllingParticipantRequest = 145,
        //    ChangeControllingParticipantCancellationRequest = 146,
        //    ChangeControllingParticipantAuthorisationRequest = 147,
        //    CancelledChangeControllingParticipantRequest = 148,
        //    ChangeControllingParticipantAuthorisation = 149,
        //    EffectedControllingParticipantChange = 150,
        //    ChangeControllingParticipantRejection = 151,
        //    RejectedChangeControllingParticipant = 152,
        //    AppliedChangeControllingParticipantRejection = 153,
        //    LoanApplication = 154,
        //    AcceptedLoanInstruction = 155,
        //    LoanApplicationCancellationRequest = 156,
        //    AdjustedLoan = 157,
        //    LoanReturnNotification = 158,
        //    AccruedLoan = 159,
        //    LoanReturnCancellationRequest = 160,
        //    ScheduledLoanInstruction = 161,
        //    BulkLoanApplication = 162,
        //    BulkLoanApproval = 163,
        //    RejectedLoanApplication = 164,
        //    CancelledLoanInstruction = 165,
        //    FullLoanInstruction = 166,
        //    ParticipantFundsNotification = 167,
        //    PaymentProviderFundsNotification = 168,
        //    ParticipantFundsObligation = 169,
        //    ParticipantFundsObligationAcknowledgement = 170,
        //    PaymentProviderFundsObligation = 171,
        //    ParticipantFundsObligationRejection = 172,
        //    PaymentProviderTransferRequest = 173,
        //    PaymentProviderTransferResponse = 174,
        //    EffectedCreateNetPosition = 175,
        //    CreateNetPositionRequest = 176,
        //    CreateNetPositionAuthorisationRequest = 177,
        //    CreateNetPositionAuthorisation = 178,
        //    AcceptedCreateNetPositionResponse = 179,
        //    CreateNetPositionRejection = 180,
        //    AppliedCreateNetPositionResponse = 181,
        //    RejectedCreateNetPosition = 182,
        //    ClearingAccountTransferRequest = 183,
        //    CreateCashSubrecordRequest = 184,
        //    CreateCashSubrecordAuthorisationRequest = 185,
        //    CreateCashSubrecordAuthorisation = 186,
        //    AcceptedCreateCashSubrecordResponse = 187,
        //    EffectedCreateCashSubrecord = 188,
        //    CreateCashSubrecordRejection = 189,
        //    AppliedCreateCashSubrecordResponse = 190,
        //    RejectedCreateCashSubrecord = 191,
        //    ZeroSumNotification = 192,
        //    CHESSDvPNotification = 193,
        //    ChangeNetPositionAttributesRequest = 194,
        //    ChangedNetPositionAttributesNotification = 195,
        //    PaymentProviderChangeCashSubrecordAttributesRequest = 196,
        //    ChangedNetPositionAttributesConfirmation = 197,
        //    ParticipantChangeCashSubrecordAttributesRequest = 198,
        //    PaymentProviderChangeCashSubrecordAttributesConfirmation = 199,
        //    ParticipantChangeCashSubrecordAttributesAuthorisation = 200,
        //    AcceptedParticipantChangeCashSubrecordAttributes = 201,
        //    ParticipantChangeCashSubrecordAttributesRejection = 202,
        //    ParticipantChangeCashSubrecordAttributesAuthorisationRequest = 203,
        //    EffectedParticipantChangeCashSubrecordAttributes = 204,
        //    AppliedParticipantChangeCashSubrecordAttributes = 205,
        //    RejectedParticipantChangeCashSubrecordAttributes = 206,
        //    SettlementCancellationNotification = 207,
        //    SettlementCancellationAcknowledgement = 208,
        //    RegistrytoCHESSConversionAuthorisation = 209,
        //    CertificatedtoCHESSConversionAuthorisationRequest = 210,
        //    RegistrytoCHESSConversionRejection = 211,
        //    IssuerSponsoredtoCHESSConversionAuthorisationRequest = 212,
        //    RegistrytoCHESSTransferAuthorisation = 213,
        //    CertificatedtoCHESSTransferAuthorisation = 214,
        //    RegistrytoCHESSTransferRejection = 215,
        //    IssuerSponsoredtoCHESSTransferAuthorisation = 216,
        //    RequestedSettlementTypeChange = 217,
        //    CHESStoCertificatedConversion = 218,
        //    CHESStoCertificatedTransfer = 219,
        //    CHESStoIssuerSponsoredConversion = 220,
        //    CHESStoIssuerSponsoredTransfer = 221,
        //    HoldingTransformation = 222,
        //    AppliedRegistryTransaction = 223,
        //    HoldingAdjustment = 224,
        //    AppliedRegistryAuthorisationResponse = 225,
        //    AppliedCodeChange = 226,
        //    TakeoverTransfer = 227,
        //    CancelledOfferorInitiatedTKOAcceptanceRequest = 228,
        //    CancelSettlementTypeChangeRequest = 229,
        //    CancelledChangeRTGSInstructionRequest = 230,
        //    UnmatchedChangeSettlementTypeRequest = 231,
        //    UpdatedRTGSInstruction = 232,
        //    AdjustedSettlementType = 233,
        //    CancelledRequesttoChangeSettlementType = 234,
        //    ParticipanttoCHESSSRNRequest = 235,
        //    CHESStoParticipantSRNRequestAcknowledgment = 236,
        //    RegistrytoCHESSSRNResponse = 237,
        //    CHESStoRegistrySRNRequest = 238,
        //    CHESStoRegistrySRNReject = 239,
        //    CHESStoRegistrySRNResponseAcknowledgment = 240,
        //    ParticipanttoCHESSHoldingBalanceRequest = 241,
        //    CHESStoParticipantSRNResponse = 242,
        //    RegistrytoCHESSHoldingBalanceResponse = 243,
        //    CHESStoRegistrySRNRejectAcknowledgment = 244,
        //    RegistrytoCHESSHoldingBalanceReject = 245,
        //    CHESStoParticipantSRNReject = 246,
        //    CHESStoParticipantHoldingBalanceRequestAcknowledgment = 247,
        //    CHESStoRegistryHoldingBalanceRequest = 248,
        //    CHESStoRegistryHoldingBalanceResponseAcknowledgment = 249,
        //    CHESStoParticipantHoldingBalanceResponse = 250,
        //    CHESStoRegistryHoldingBalanceRejectAcknowledgment = 251,
        //    CHESStoParticipantHoldingBalanceReject = 252,
        //    AuthoriseRTGSInstructionConfirmation = 253,
        //    UnmatchedChangeRTGSInstructionRequest = 254,
        //    RequestedRTGSInstructionChange = 255,
        //    RTGSDualEntryNotification = 256,
        //    UnmatchedRTGSDualEntryNotification = 257,
        //    RTGSNotificationCancellationRequest = 258,
        //    UnmatchedRTGSDualEntryRequest = 259,
        //    RTGSDualEntryCancellationRequest = 260,
        //    RTGSDualEntryCancellationRemoval = 261,
        //    ChangeRTGSInstructionRequest = 262,
        //    UnmatchedRTGSInstructionCancellationRequest = 263,
        //    ChangeRTGSInstructionCancellationRequest = 264,
        //    RemovedRTGSInstructionCancellationRequest = 265,
        //    MaintainRTGSInstructionRequest = 266,
        //    AuthoriseScheduledRTGSInstruction = 267,
        //    CheckingRBAFundsQueueAdvice = 268,
        //    SettlementTypeChangeRequest = 269,
        //    RTGSInstructionReadytoSettleAdvice = 270,
        //    HoldingSubpositionDetail = 271,
        //    ReportingRequest = 272,
        //    CumEntitlementDailyBalance = 273,
        //    ReportingRequestCancellation = 274,
        //    CumEntitlementNetMovement = 275,
        //    HoldingDailyBalance = 276,
        //    HoldingNetMovement = 277,
        //    HoldingRegistrationDetails = 278,
        //    AggregatedForeigntoForeignAllocations = 279,
        //    RightsAccepted = 280,
        //    RejectedTransaction = 281,
        //    CumEntitlementBalance = 282,
        //    HoldingBalance = 283,
        //    TotalCumEntitlementBalance = 284,
        //    AcceptedReportingRequest = 285,
        //    ArchivedSub_Register = 286,
        //    CancelledReportingRequest = 287,
        //    TotalHoldingBalance = 288,
        //    TaxFileNumberOrAustralianBusinessNumberAdvice = 289,
        //    NotifiedTaxFileNumberOrAustralianBusinessNumber = 290,
        //    AcceptedTaxFileNumberOrAustralianBusinessNumberAdvice = 291,
        //    EndofReporting = 292,
        //    InvalidTransaction = 293,
        //    CHESSEventNotification = 294,
        //    LevyNotification = 295,
        //    RevisedHolderRegistrationDetails = 296,
        //    ReversedLevyNotification = 297,
        //    ScheduledPaymentInstruction = 298,
        //    AggregatedPaymentInstruction = 299,
        //    AcceptedPaymentSet = 300,
        //    PaymentSetTotalRecord = 301,
        //    CloseOutNotification = 302,
        //    CancelledPaymentSetNotification = 303,
        //    TopSecurityHolderReport = 304,
        //    CollateralReleaseRequest = 305,
        //    EffectedASXClearTransaction = 306,
        //    CollateralRemovalAuthorisation = 307,
        //    CollateralRemovalRejection = 308,
        //    AcceptedCollateral = 309,
        //    RejectedCollateral = 310,
        //    CollateralRequest = 311,
        //    CollateralRemovalAuthorisationRequest = 312,
        //    CashSubrecordDetails = 313,
        //    CashSubrecordTotal = 314,
        //    ETCTradeAdvice = 315,
        //    ETCTrade = 316,
        //    ETCTradeAllocationAdvice = 317,
        //    ETCTradeAdviceAcknowledgement = 318,
        //    ETCTradeRejectionAdvice = 319,
        //    ETCTradeAllocation = 320,
        //    ContractNoteAdvice = 321,
        //    ETCTradeAllocationAcknowledgement = 322,
        //    ContractNoteRejectionAdvice = 323,
        //    ETCTradeRejection = 324,
        //    AllocationCancellationAdvice = 325,
        //    ETCTradeRejectionAcknowledgement = 326,
        //    ETCSettlementAdvice = 327,
        //    ContractNote = 328,
        //    ETCSettlementCancellationAdvice = 329,
        //    ContractNoteAdviceAcknowledgment = 330,
        //    ETCTradeCancellationAdvice = 331,
        //    ContractNoteRejection = 332,
        //    ETCContractNoteCancellationAdvice = 333,
        //    ContractNoteRejectionAcknowledgement = 334,
        //    AllocationCancellation = 335,
        //    AllocationCancellationAcknowledgement = 336,
        //    ETCSettlement = 337,
        //    ETCSettlementAdviceAcknowledgement = 338,
        //    ETCSettlementCancellation = 339,
        //    ETCSettlementCancellationAcknowledgment = 340,
        //    ETCTradeCancellation = 341,
        //    ETCTradeCancellationAcknowledgement = 342,
        //    ETCContractNoteCancellation = 343,
        //    ETCContractNoteCancellationAcknowledgement = 344,
        //    ControllingPIDandHolderStatusRequest = 345,
        //    ControllingPIDandHolderStatusResponse = 346,
        //    CancelledTransferorConversionRequest = 347,
        //    TakeoverAcceptanceRejection = 348,
        //    TakeoverAcceptanceRemovalAuthorisationRequest = 349,
        //    TakeoverAcceptanceRemovalAuthorisation = 350,
        //    TakeoverAcceptanceNotification = 351,
        //    TakeoverAcceptanceRemovalRejection = 352,
        //    EffectedOfferorTransaction = 353,
        //    OfferorTakeoverAcceptanceRemoval = 354,
        //    RejectedOfferorTakeoverAcceptance = 355,
        //    OfferorTakeoverAcceptance = 356,
        //    CHESStoIssuerSponsoredFundConversionRequest = 357,
        //    CHESSConversionRequesttoIssuerSponsoredFund = 358,
        //    EffectedCHESSConversionRequesttoIssuerSponsoredFund = 359,
        //    IssuerSponsoredFundtoCHESSConversionRequest = 360,
        //    IssuerSponsoredFundtoCHESSConversionAuthorisationRequest = 361,
        //    AcceptedParticipantRequest = 362,
        //    ConversionAuthorisationIssuerSponsoredFundto = 363,
        //    FundResponse = 364,
        //    EffectedConversionIssuerSponsoredFundto = 365,
        //    ConversionRejectionIssuerSponsoredFundto = 366,
        //    RejectedConversionIssuerSponsoredFundtoCHESS = 367,
        //    ApplicationRequest = 368,
        //    ApplicationOrderRequest = 369,
        //    ApplicationOrderOrPaymentPlanApplicationResponse = 370,
        //    EffectedApplicationOrderOrPaymentPlanApplicationResponse = 371,
        //    ScheduledSettlementPaymentInstruction = 372,
        //    UnitAdjustment = 373,
        //    EffectedFundUnitAdjustment = 374,
        //    ForeignTaxStatus = 375,
        //    ForeignTaxStatusDetails = 376,
        //    InvestorDetails = 377,
        //    ParticipantInvestorDetails = 378,
        //    CancelledFundRequest = 379,
        //    RequestingFundsApproval = 380,
        //    RTGSSettlementMovement = 381,
        //    RTGSFundsMovement = 382,
        //    HoldingAdvice = 383,
        //    HoldingAdviceAcknowledgement = 384,
        //    HoldingAdviceAcceptance = 385,
        //    HoldingAdviceNotification = 386,
        //    HoldingAdviceRejection = 387,
        //    EffectedRegistryTransaction = 388,
        //    AcceptedHoldingAdvice = 389,
        //    RejectedHoldingAdvice = 390,
        //    RedemptionRequest = 391,
        //    RedemptionOrderRequest = 392,
        //    RedemptionOrderResponse = 393,
        //    EffectedRedemptionOrderRequest = 394,
        //    FundOrderCancellationRequest = 395,
        //    OrderCancellationRequest = 396,
        //    SwitchRequest = 397,
        //    SwitchOrderRequest = 398,
        //    SwitchOrderResponse = 399,
        //    EffectedSwitchOrderRequest = 400,
        //    UpdateOrder = 401,
        //    EffectedUpdateOrder = 402,
        //    ReminderNotice = 403,
        //    DistributionStatement = 404,
        //    DistributionStatementAdvice = 405,
        //    DistributionReinvestmentNotification = 406,
        //    EffectedDistributionReinvestmentPlanAdvice = 407,
        //    CancelledFundsSettlementPaymentInstruction = 408,
        //    ChangeSettlementDate = 409,
        //    HoldingDailyFundBalance = 410,
        //    HoldingNetFundBalance = 411,
        //    HoldingFundBalance = 412,
        //    TotalSecurityFundBalance = 413,
        //    FullIssuerSponsoredFundtoCHESSConversion = 414,
        //    FullCHESStoIssuerSponsoredFundConversion = 415,
        //    ParticipanttoCHESSFundBalanceRequest = 416,
        //    CHESStoRegistryFundBalanceRequest = 417,
        //    RegistrytoCHESSFundBalanceResponse = 418,
        //    CHESStoParticipantFundBalanceResponse = 419,
        //    RegistrytoCHESSFundBalanceRejection = 420,
        //    CHESStoParticipantFundBalanceReject = 421,
        //    TotalSecurityFundHolderReport = 422,
        //    UnitReversalNotification = 423,
        //    EffectedUnitReversalNotification = 424,
        //    CHESStoCHESSFundTransferRequest = 425,
        //    EffectedFundTransfer = 426,
        //    CHESSToCHESSFundTransferRequestDetails = 427,
        //    CHESSToCHESSFundTransferResponse = 428,
        //    RejectedRegistryAuthorisation = 429,
        //    DistributionElectionRequest = 430,
        //    DistributionElectionAuthorisationRequest = 431,
        //    DistributionElectionRegistryAuthorisation = 432,
        //    AcceptedDistributionElectionRequest = 433,
        //    DistributionElectionRegistryRejection = 434,
        //    IncomeStatementAuthorisationRequest = 435,
        //    IncomeStatementRequest = 436,
        //    AcceptedMarginCoverCreationRequest = 437,
        //    MarginCoverCreationRequest = 438,
        //    MarginCoverAuthorisationRequest = 439,
        //    MarginCoverCreationAuthorisation = 440,
        //    EffectedMarginCoverReleaseandTransfer = 441,
        //    MarginCoverCreationRejection = 442,
        //    AcceptedMarginCoverCreation = 443,
        //    MarginCoverRemovalRequest = 444,
        //    ReducedMarginCover = 445,
        //    MarginCoverRemovalAuthorisation = 446,
        //    AcceptedMarginCoverRemovalRequest = 447,
        //    IncomeStatementAuthorisation = 448,
        //    MarginCoverRemovalAuthorisationRequest = 449,
        //    ASXClearRemovalMarginCover = 450,
        //    AcceptedIncomeStatementRequest = 451,
        //    ASXClearMarginCoverRemovalRequest = 452,
        //    IncomeStatementRejection = 453,
        //    ExcessCashStandingInstructionRequest = 454,
        //    DailyInterestEarnedNotification = 455,
        //    ExcessCashStandingInstructionAuthorisation = 456,
        //    ExcessCashStandingInstructionRejection = 457,
        //    MarginSettlementNotification = 458,
        //    MarginSettlementAmountChangeRequest = 459,
        //    MarginSettlementAmountChangeAuthorisation = 460,
        //    MarginSettlementAmountChangeRejection = 461,
        //    CollateralStatementNotification = 462,
        //    EndStatementNotification = 463,
        //    MarginCoverRemovalRejection = 464,
        //    ExcessCashStandingInstructionAuthorisationRequest = 465,
        //    AcceptedExcessCashStandingInstructionRequest = 466,
        //    EffectedExcessCashStandingInstructionRequest = 467,
        //    RejectedExcessCashStandingInstructionRequest = 468,
        //    DailyInterestEarnedStatement = 469,
        //    MarginSettlementAdvice = 470,
        //    MarginSettlementAmountChangeAuthorisationRequest = 471,
        //    AcceptedMarginSettlementAmountChangeRequest = 472,
        //    EffectedMarginSettlementAmountChange = 473,
        //    RejectedMarginSettlementAmountChange = 474,
        //    CollateralStatement = 475,
        //    EndStatement = 476,
        //    RejectedMarginCoverRemovalRequest = 477,
        //    RegistryIncomeStatementPartA = 478,
        //    AcceptedRegistryIncomeStatementSet = 479,
        //    RegistryIncomeStatementPartB = 480,
        //    RejectedRegistryIncomeStatementSet = 481,
        //    RegistryIncomeStatementPartCAI = 482,
        //    ParticipantIncomeStatementPartA = 483,
        //    RegistryIncomeStatementPartCCG = 484,
        //    ParticipantIncomeStatementPartB = 485,
        //    RegistryIncomeStatementPartCFI = 486,
        //    ParticipantIncomeStatementPartCAI = 487,
        //    RegistryIncomeStatementPartCNA = 488,
        //    ParticipantIncomeStatementPartCCG = 489,
        //    RegistryIncomeStatementPartCOD = 490,
        //    ParticipantIncomeStatementPartCFI = 491,
        //    EndRegistryIncomeStatementSet = 492,
        //    ParticipantIncomeStatementPartCNA = 493,
        //    ParticipantIncomeStatementPartCOD = 494,
        //    EndParticipantIncomeStatementSet = 495
        //}
        #endregion CHESS Message Types





        /// <Summary>
        /// Represents a rejected reason.
        /// </Summary>
        #region Rejected reason
        public enum RejectedReason
        {
            // repeated items
            // 653 '06137'
            // 655 '06137'
        }
        #endregion Rejected reason
    }
}